### ISSUE TITLE
트레사 대사 오타

### ISSUE THREAD

**Issue by Kimwookyum** [Joonie86/Joonie86.github.io#10]
![트레사 2장 오타](https://user-images.githubusercontent.com/53118311/61579171-b2f07000-ab3c-11e9-91c9-1ba02a1fbe00.PNG)

트레사 2장 쿼리크레스트에서 아리가 벽섬석 다 팔고 난 뒤, 고기만두 사러갔을 때 입니다.
트레사 대사에 '......그리면' 이라고 합니다. '그러면'의 오타

**Comment by Joonie86** [comment]
@Kimwookyum 제보 감사 합니다. 금일 배포된 8월5일자 패치에 반영 되어있습니다.
