### ISSUE TITLE
Help: Octopath traveler-Apply new EN Talk & GameText for Switch

### ISSUE THREAD

**Issue by DKH6789** [Joonie86/Joonie86.github.io#11]
Hi Joonie86.

I'm working on localization the game Octopath Traveler from English to my mother language-Vietnamese. The team has only 1 member, me. I finished the font and translated almost 25,000 lines in 2 months.

On Steam, everything works fine (it is easy). But on Switch, I tried my best but there's no way to force the game to use the TalkData_EN and GameText_EN. I did exact waht you did on Switch with no ips files, and it does not work. I thought no one can help me, ultil I found your finished project (congra)!

So, I write this "Issue" to ask for your help to crete ips to apply the new translated file to the game.
I do hope you can help me with this. Thanks so much.
p/s: this is the demo version of the game in Vietnamese
https://www.youtube.com/watch?v=s219xQ9Tido

**Comment by DKH6789** [comment]
Hello? Are you still here?

**Comment by Joonie86** [comment]
> Hello? Are you still here?

Sorry, I didn't check this issue until today, if you can provide the "main" file from exefs folder then I can take a look. I used IPS patch because I wanted to force Japanese text over non Japanese system UI.
