### ISSUE TITLE
게임 패치로 인한 실행 불가현상이 있습니다 ㅠ

### ISSUE THREAD

**Issue by yanggwangbok** [Joonie86/Joonie86.github.io#13]
스팀에서 할인하길래 뒤늦게 캡틴 츠바사를 입문하려고 합니다

소중한 한글패치를 받아서 실행을 해보았지만 계속 튕기길래 찾아보니

버전이 바뀌면서 같은 현상을 겪는 분들이 계시더라구요..

혹시 수정 및 재배포가 불가할까요 ..? ㅠ_ㅠ

**Comment by Joonie86** [comment]
1.46 대응 패치 오늘자 갱신 되었습니다.
