### ISSUE TITLE
사이러스로 진행시 튜토리얼 오류가 있습니다.

### ISSUE THREAD

**Issue by Garigui** [Joonie86/Joonie86.github.io#2]
도서 찾기위해서 탐문을 시작하려고 할때 뜨는 튜토리얼에서

스샷은 액션에 대한 내용인데 번역된 튜토리얼 내용은 BP 사용에 관한 튜토리얼로 나옵니다.

다른케릭터로 시작해보지 않아서 다른케릭터는 어떤지 모르겠지만 사이러스 부분은

스샷과 번역이 다릅니다.

**Comment by Joonie86** [comment]
피드백 감사 합니다. 해당 내용은 27일자 패치로 확인 하신 건가요?

**Comment by Joonie86** [comment]
> 도서 찾기위해서 탐문을 시작하려고 할때 뜨는 튜토리얼에서
> 
> 스샷은 액션에 대한 내용인데 번역된 튜토리얼 내용은 BP 사용에 관한 튜토리얼로 나옵니다.
> 
> 다른케릭터로 시작해보지 않아서 다른케릭터는 어떤지 모르겠지만 사이러스 부분은
> 
> 스샷과 번역이 다릅니다.

![image](https://user-images.githubusercontent.com/8692743/60366344-1b19bf00-99a0-11e9-8add-10af4547d127.png)

피드백 감사 합니다. 해당 내용은 이미 최신 버젼 (6월27일자) 기준으로 이미 수정된 사항 입니다.

![image](https://user-images.githubusercontent.com/8692743/60366427-616f1e00-99a0-11e9-9d29-89710ddc78bf.png)
