### ISSUE TITLE
오필리아 1장 퀘스트 완료 후 감옥 서브퀘스트 대화 중에서

### ISSUE THREAD

**Issue by Garigui** [Joonie86/Joonie86.github.io#3]
무고한 시민이 감옥에 갇혀 있는 서브퀘스트 진행 중

병사의 대사 중에서 정확한 내용은 기억이 안나지만 "그레 그럴 수 있겠군" 에서

"그레 -> 그래" 로 수정이 필요할꺼 같습니다

이전에 제가 피드백 드렸던 부분은 27일 패치로 수정된거 확인하였습니다.

수고가 많으십니다~ 감사합니다

**Comment by Joonie86** [comment]
> 무고한 시민이 감옥에 갇혀 있는 서브퀘스트 진행 중
> 
> 병사의 대사 중에서 정확한 내용은 기억이 안나지만 "그레 그럴 수 있겠군" 에서
> 
> "그레 -> 그래" 로 수정이 필요할꺼 같습니다
> 
> 이전에 제가 피드백 드렸던 부분은 27일 패치로 수정된거 확인하였습니다.
> 
> 수고가 많으십니다~ 감사합니다

언급하신 대사는 아무리 봐도 나오지가 않지만

"<U4515>...... 으음, 그레 사고라는 건가#좋아, 잠깐 기다려라<E>" <- 이 대사는 나오네요. 이거 말씀 하신거 맞나요?

**Comment by Garigui** [comment]
네~ 그 부분 맞습니다.
제가 퀘스트 내용을 잘 기억하지 못해서 죄송합니다.

**Comment by Joonie86** [comment]
> 네~ 그 부분 맞습니다.
> 제가 퀘스트 내용을 잘 기억하지 못해서 죄송합니다.

7월 2일자 패치 등록하면서 해당 사항 반영 하였습니다.
