### ISSUE TITLE
테리온 1장 퀘스트 대사 중에서

### ISSUE THREAD

**Issue by Garigui** [Joonie86/Joonie86.github.io#5]
집사랑 보스전 후 대화에서

......뭐하는 놈이야, 너는?
도저히 일반인의 움직이 아니었어

이 부분에서 `움직이` 가 `움직임이` 로 수정되어야 할꺼 같습니다.

**Comment by Garigui** [comment]
추가적인 부분입니다.

1. 꽤나 잘 알고 있는 것같은데-
-> `것같은데-` 부분을 `것 같은데-` 띄어쓰기가 필요합니다.
2. 그것참 반가운 소리군요
그럼 거래는 성립니다.
->`그것참` 부분을 `그것 참` 띄어쓰기가 필요합니다.
3. 하하--죄송합니다.
저도 장사꾼이라
->`하하--죄송합니다` 부분을 `하하-- 죄송합니다` 띄어쓰기가 필요합니다.

**Comment by Joonie86** [comment]
> 집사랑 보스전 후 대화에서
> 
> ......뭐하는 놈이야, 너는?
> 도저히 일반인의 움직이 아니었어
> 
> 이 부분에서 `움직이` 가 `움직임이` 로 수정되어야 할꺼 같습니다.

피드백 감사 합니다. 다음 버젼에 모두 반영 하겠습니다.

**Comment by Joonie86** [comment]
7월 12일자 패치에서 반영 되었습니다. 피드백 감사합니다. @Garigui

https://joonie86.github.io/generic.html
