### ISSUE TITLE
프림로제 1장 이벤트 중 주점에서

### ISSUE THREAD

**Issue by Garigui** [Joonie86/Joonie86.github.io#7]
까마귀 남자 주점 밖으로 나간 후 지배인 대사 입니다.

손님을 내버두고 가게를 나오는 무희가 있을 줄이야

`내버두고` 를 `내버려두고` 로 수정 부탁드립니다.

**Comment by Joonie86** [comment]
7월 12일자 패치에서 반영 되었습니다. 피드백 감사합니다. @Garigui

https://joonie86.github.io/generic.html
