### ISSUE TITLE
2장 이후로 파티 대화 말인데요

### ISSUE THREAD

**Issue by Garigui** [Joonie86/Joonie86.github.io#8]
케릭터 말투가 일정하지 않고

어른스럽다가 아이스럽게 말투가 왔다갔다 하는 경향이 있습니다.

예를들면 사이러스 2장 진행 중 하수도에 진입 후 파티 대화를 하는데

사이러스 - 테리온 간의 대화에서 사이러스 말투가 그렇습니다.

말투 통일성이 필요할꺼 같습니다.

**Comment by Joonie86** [comment]
7월 12일자 패치에서 반영 되었습니다. 피드백 감사합니다. @Garigui

https://joonie86.github.io/generic.html
