### ISSUE TITLE
알핀 2장 퀘스트 대화 중에서

### ISSUE THREAD

**Issue by Garigui** [Joonie86/Joonie86.github.io#9]
푸른 이끼 맵에서 바네사랑 만나서 하는 대화 중

알핀이 하는 대사 중에서 

병으로부터 약사를 지키는게 약사 라는 부분에서

앞쪽 `약사를` `약자를` 로 바껴야 합니다.

**Comment by Joonie86** [comment]
7월 12일자 패치에서 반영 되었습니다. 피드백 감사합니다. @Garigui

https://joonie86.github.io/generic.html
